// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.17.0

package db

import (
	"time"

	"github.com/google/uuid"
)

type Asset struct {
	ID        uuid.UUID `json:"id"`
	AssetName string    `json:"asset_name"`
	Owner     uuid.UUID `json:"owner"`
	Tester    uuid.UUID `json:"tester"`
}

type Result struct {
	ID         uuid.UUID `json:"id"`
	ResultName string    `json:"result_name"`
	Assets     uuid.UUID `json:"assets"`
	Tester     uuid.UUID `json:"tester"`
}

type Session struct {
	ID           uuid.UUID `json:"id"`
	Username     string    `json:"username"`
	RefreshToken string    `json:"refresh_token"`
	UserAgent    string    `json:"user_agent"`
	ClientIp     string    `json:"client_ip"`
	IsBlocked    bool      `json:"is_blocked"`
	ExpiresAt    time.Time `json:"expires_at"`
	CreateAt     time.Time `json:"create_at"`
}

type User struct {
	ID             uuid.UUID `json:"id"`
	Username       string    `json:"username"`
	HashedPassword string    `json:"hashed_password"`
	FullName       string    `json:"full_name"`
	Role           string    `json:"role"`
	Email          string    `json:"email"`
	CreateAt       time.Time `json:"create_at"`
}
